### ISSUE TITLE
uluac.exe Syntax error on alltest.lua

### ISSUE THREAD

**Issue by peterson79** [deemess/uLua#1]
I have compiled the code and am trying to compile the "test\alltest.lua" script with uluac.exe, when I do I get this on the command line output:

TK_FUNCTION function
P_SCOPE_EMPTY
P_STATLIST_EMPTY
TK_NAME loadtest
TK_LPAREN
TK_RPAREN
Syntax error:8 on line: 2 token TK_RPAREN

I have tried this with Visual Studio, and with make on OS X, same thing...  I am not familiar enough with the parser to figure out where it is choking...

**Comment by dima-umkk** [comment]
This test for old version.
This project starts as Lua bytecode interpreter. As compiler I used standard Lua compiler.
Now I desided to write my own Lua compiler to compile and execute Lua code directly on chip.
Currently compiler doesnt support function definition. Going to implement it after memory management as it require many allocations.
You could try to play with REPL (ulua.exe)
Just write the code in console and check output.
For now ulua supports: expressions, while, if/then/else and print function
For example:
a = 10; while (a > 0) do print(a); a=a-1; end

**Comment by dima-umkk** [comment]
Actually I need to change readme file as it is not actual :)

**Comment by dima-umkk** [comment]
I have updated alltest.lua. Please try now.
