### ISSUE TITLE
Please Explain How Native Calls Work

### ISSUE THREAD

**Issue by jockm** [deemess/uLua#3]
I can see some provision for them in the VM (See vm.c line 445), but I don't see how the condition `curstate->reg[a].type == VAR_NATIVE_FUNC` is made true.  How do I register functions with the VM

**Comment by dima-umkk** [comment]
In native.c there are init native function which registers all desired natives in global namespace so they should be available in runtime. For example there is print native function implementation there.

**Comment by jockm** [comment]
Awesome, thank you very much!
